language: java
sudo: required
jdk:
- openjdk14
git:
  quiet: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
assemble: true
install: true
jobs:
  include:
  - stage: build
    script: "./gradlew build javadocJar checkMappings -S -i"
  - stage: deploy
    before_install: sudo apt-get install pandoc
    install: pandoc --from markdown --to html5 --standalone -o readme.html README.md
    script: "./gradlew build javadocJar bintrayUpload publishMavenGitHubPublicationToGitHubRepository -S -i"
    deploy:
      - provider: pages
        github_token: "$GITHUB_OAUTH_TOKEN"
        local_dir: build/docs/javadoc
        keep_history: true
        skip_cleanup: true
        target_branch: gh-pages
        on:
          branch: master
      - provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file_glob: true
        file: build/libs/*
        skip_cleanup: true
        on:
          tags: true

stages:
- build
- name: deploy
  if: repo = liachmodded/yarn AND env(bintray_key) AND env(GITHUB_OAUTH_TOKEN) AND branch = MAIN
env:
  global:
  - TERM=dumb
notifications:
  email: false
